### PR TITLE
Rewrote code to be better

### PR DESCRIPTION
**Pull request by kontakt**

### CODE REVIEW

**Comment by tcannon79** [comment]
Thank you so much for your contribution. I think we can do it even better as well, I have some ideas, I think we need to make it more real time. so basically updating a currentHertz variable and then calculating whether the inductor should be HIGH or LOW. this way you don't have to wait the 400ms at max distance if something is moving in really quickly.

Thoughts

**Comment by kontakt** [comment]
It would be pretty simple to get the program to pull a lot more samples in continuously by removing the delays and replacing them with timer based events. That's the way I do most of my events in code like this. See BlinkWithoutDelay for an example in the arduino examples. You have to be careful changing frequencies mid cycle. It's really easy to get strange and confusing feedback if you can do that. Picture swinging your arm, what would the value it returned be? It would be variable and a weird feel. If you want faster feedback, you need to increase the frequency of the feedback. Instead of turning it on once and then off for a duration, why not use pwm and have a more responsive output?

**Comment by tcannon79** [comment]
I will check PWM tonight. Something tells me we tried it and it didn't work.

**Comment by kontakt** [comment]
If pwm doesn't work, I'd say go with a shorter pulse structure. 400ms max is a bit long.

**Comment by tcannon79** [comment]
yeah we are starting to come to that conclusion as well, we also got a BN transferring numeric data to the user. we are fucking with that right meow.

**Comment by kontakt** [comment]
How strong are the pulses, and can you tell the strength of the inductor with different currents?

**Comment by tcannon79** [comment]
we haven't yet tried different current strengths. the 20mA from the pin is sufficient to very clear pulse on a 10mH inductor

**Comment by kontakt** [comment]
The best output I could imagine would be a varied current and thus field based on the input. Analog, rather than digital.

**Pull request merged**
